import {test,after} from 'node:test';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';import {mkdtempSync,mkdirSync,writeFileSync,readFileSync,existsSync} from 'node:fs';import {DatabaseSync} from 'node:sqlite';import {randomBytes} from 'node:crypto';import path from 'node:path';import {fileURLToPath} from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url));mkdirSync(path.join(root,'work'),{recursive:true});const scratch=mkdtempSync(path.join(root,'work','ops-test-')),source=path.join(scratch,'source.sqlite'),journal=source+'.deletions.sqlite';
function run(command,args=[],input={},dbPath=source,journalPath=journal){return new Promise(resolve=>{const child=spawn(process.execPath,[path.join(root,'ops.mjs'),command,...args],{env:{...process.env,DB_PATH:dbPath,RETENTION_JOURNAL_PATH:journalPath}});let stdout='',stderr='';child.stdout.on('data',x=>stdout+=x);child.stderr.on('data',x=>stderr+=x);child.on('close',code=>resolve({code,stdout,stderr}));child.stdin.end(JSON.stringify(input))})}
test('운영 도구: 합성 원장 설정·검수 게이트·암호화 백업·최신 삭제 재적용',async()=>{
 let result=await run('init-director',[],{id:'synthetic-director',password:'Synthetic-Only-2026!'});assert.equal(result.code,0,result.stderr);
 const fixture={batch_id:'ops-synthetic',source:{file:'합성 파일',tab_id:1284097826,header_row:4,version:'v1.1'},cutoff:'2026-10-03T06:00:00Z',students:[{source_key:'s1',number:'MBR-000999',name:'합성 복원 학생',axis:'개인과외',status:'재원',minor:false}],products:[],enrollments:[],lessons:[]};
 const inputFile=path.join(scratch,'fixture.json');writeFileSync(inputFile,JSON.stringify(fixture));assert.equal((await run('apply-import',[inputFile])).code,0);
 const checklist=path.join(scratch,'review.json');writeFileSync(checklist,JSON.stringify({policy_review:{approved:false}}));assert.equal((await run('begin-operation',[checklist])).code,1);
 const authDB=new DatabaseSync(source);authDB.prepare('INSERT INTO sessions VALUES(?,?,?,?,?)').run('synthetic-digest','synthetic-director',0,Date.now(),Date.now());authDB.prepare('UPDATE accounts SET temp_hash=?,temp_until=?,temp_used=0').run('synthetic-hash',Date.now()+3600000);authDB.close();
 const key=randomBytes(32).toString('hex'),encrypted=path.join(scratch,'backup.pdmbak');assert.equal((await run('backup',[encrypted],{key})).code,0);assert.ok(!readFileSync(encrypted).includes(Buffer.from('合成')));assert.ok(!readFileSync(encrypted).includes(Buffer.from('합성 복원 학생')));
 const badTarget=path.join(scratch,'bad.sqlite');assert.equal((await run('restore',[encrypted],{key:randomBytes(32).toString('hex')},badTarget)).code,1);assert.equal(existsSync(badTarget),false);
 const db=new DatabaseSync(source);const student=db.prepare("SELECT * FROM records WHERE kind='students'").get();db.prepare('UPDATE records SET data=? WHERE id=?').run(JSON.stringify({...JSON.parse(student.data),status:'종료',delete_due:'2000-01-01T00:00:00Z',ended_at:'1999-01-01T00:00:00Z'}),student.id);db.close();assert.equal((await run('purge')).code,0);
 const target=path.join(scratch,'restore.sqlite');result=await run('restore',[encrypted],{key},target);assert.equal(result.code,0,result.stderr);assert.equal(JSON.parse(result.stdout).removed,1);
 const restored=new DatabaseSync(target);assert.equal(restored.prepare("SELECT count(*) n FROM records WHERE kind='students'").get().n,0);assert.equal(restored.prepare('SELECT count(*) n FROM sessions').get().n,0);assert.equal(restored.prepare('SELECT count(*) n FROM accounts WHERE temp_hash IS NOT NULL').get().n,0);assert.equal(restored.prepare('SELECT value FROM metadata WHERE key=?').get('restore_state').value,'verified');restored.close();
 assert.equal((await run('restore',[encrypted],{key},target)).code,1);
});

test('운영 시작 차단·합성 최댓값이 실제 초기번호에 섞이지 않음',async()=>{const newDB=path.join(scratch,'empty.sqlite');let result=await run('init-director',[],{id:'synthetic-two',password:'Synthetic-Second-2026!'},newDB,newDB+'.deletions.sqlite');assert.equal(result.code,0);const db=new DatabaseSync(newDB);assert.equal(db.prepare('SELECT value FROM counters').get().value,0);assert.equal(db.prepare("SELECT count(*) n FROM accounts WHERE id='director-demo'").get().n,0);db.close();const status=await new Promise(resolve=>{const child=spawn(process.execPath,[path.join(root,'server.mjs')],{env:{...process.env,NODE_ENV:'production',APP_MODE:'production',PUBLIC_ORIGIN:'https://synthetic.example',DB_PATH:newDB,PORT:'0'}});let stderr='';child.stderr.on('data',x=>stderr+=x);child.on('close',code=>resolve({code,stderr}))});assert.equal(status.code,1);assert.ok(status.stderr.includes('reviewed transition to operating required'))});
