import {test,after} from 'node:test';import assert from 'node:assert/strict';
process.env.NODE_ENV='test';process.env.DB_PATH=':memory:';
const {server,db,sweep,setTestClock}=await import('./server.mjs');
await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;
async function call(p,b,c,m=b?'POST':'GET'){let r=await fetch(base+'/api/'+p,{method:m,headers:{'Content-Type':'application/json',Cookie:c||''},body:b?JSON.stringify(b):undefined});return {status:r.status,d:await r.json(),c:r.headers.get('set-cookie')?.split(';')[0]}}
let ac=(await call('login',{id:'director-demo',password:'Demo-Director-2026!',mode:'director'})).c;
const list=k=>call('admin/'+k,null,ac);const create=(k,b)=>call('admin/'+k,{...b,operation_id:crypto.randomUUID()},ac);
after(()=>server.close());
test('입력·상태·날짜·서버 보존필드 검증',async()=>{let p=(await list('products')).d[0],s=(await list('students')).d[0];assert.equal((await create('products',{...p,name:'잘못된 상태',status:'오류'})).status,400);assert.equal((await create('lessons',{student:s.id,enrollment:(await list('enrollments')).d[0].id,date:'2026-02-30',time:'14:00',status:'완료',type:'정규',published:false})).status,400);assert.equal((await call('admin/students/'+s.id,{...s,delete_due:'2000-01-01'},ac,'PUT')).status,400);assert.equal((await create('students',{name:'합성',axis:'개인과외',status:'재원',minor:'false'})).status,400);assert.equal((await call('password',null,ac)).status,405)});
test('공개 수정 해제·재공개·학생 허용필드',async()=>{let l=(await list('lessons')).d[0];let r=await call('admin/lessons/'+l.id,{...l,task:'수정 과제'},ac,'PUT');assert.equal(r.d.published,false);r=await call('admin/lessons/'+l.id,{...r.d,published:true},ac,'PUT');assert.equal(r.d.published,true);let auth=await call('login',{id:'MBR-000742',password:'1234',mode:'student'});assert.equal((await call('student',null,auth.c)).status,403);auth=await call('password',{password:'Quality-Student-2026!',confirm:'Quality-Student-2026!'},auth.c);let view=(await call('student',null,auth.c)).d;assert.equal(view.lessons[0].task,'수정 과제');assert.ok(!JSON.stringify(view).includes('내부'));assert.ok(!('guardian' in view));assert.equal((await call('student?id=999',null,auth.c)).status,403);assert.equal((await call('admin/products',null,auth.c)).status,403)});
test('번호 변경·번호 재사용 거절·기존 세션 폐기',async()=>{let s=(await list('students')).d[0];let auth=await call('login',{id:s.number,password:'Quality-Student-2026!',mode:'student'});let r=await call('admin/number-change/'+s.id,{operation_id:crypto.randomUUID(),version:s.version,number:'MBR-000900',reason:'합성 정정'},ac);assert.equal(r.status,200);assert.equal((await call('student',null,auth.c)).status,401);assert.equal((await call('login',{id:'MBR-000742',password:'Quality-Student-2026!',mode:'student'})).status,401);assert.equal((await call('admin/number-change/'+s.id,{operation_id:crypto.randomUUID(),version:r.d.version,number:'MBR-000742',reason:'재사용'},ac)).status,400);assert.equal((await call('login',{id:'MBR-000900',password:'Quality-Student-2026!',mode:'student'})).status,200)});
test('상품 전환 원자성·연결 수업·재시도',async()=>{let e=(await list('enrollments')).d[0];let p=(await create('products',{name:'합성 전환 상품',axis:'성인 스튜디오',status:'사용'})).d;let b={version:e.version,start:'2026-10-01',product:p.id,division:'교습소',operation_id:'transition-test'};assert.equal((await call('admin/transition/'+e.id,b,ac)).status,400);assert.equal((await list('enrollments')).d[0].end,'');b.start='2026-11-01';let r=await call('admin/transition/'+e.id,b,ac);assert.equal(r.status,200);assert.equal((await call('admin/transition/'+e.id,b,ac)).d.id,r.d.id);assert.equal((await list('enrollments')).d.length,2)});
test('임시값 중복발급·동시사용·제한세션 실패 재시도',async()=>{let s=(await list('students')).d[0];let b={verified:true,method:'합성 대면확인',operation_id:'temp-once'};let r=await call('admin/accounts/'+s.id,b,ac);assert.ok(r.d.temporary);assert.equal((await call('admin/accounts/'+s.id,b,ac)).d.temporary,undefined);assert.equal(db.prepare('SELECT count(*) n FROM verification').get().n,1);let rs=await Promise.all([1,2].map(()=>call('login',{id:s.number,password:r.d.temporary,mode:'student'})));assert.deepEqual(rs.map(x=>x.status).sort(),[200,401]);let c=rs.find(x=>x.status===200).c;assert.equal((await call('password',{password:'bad',confirm:'bad'},c)).status,400);assert.equal((await call('student',null,c)).status,403);assert.equal((await call('password',{password:'Quality-Reset-2026!',confirm:'Quality-Reset-2026!'},c)).status,200);assert.equal((await call('student',null,c)).status,401)});
test('KST 종료 경계·두 보존기간·개인정보 캐시 제거',async()=>{setTestClock(Date.parse('2026-10-02T14:59:59Z'));let s=(await create('students',{name:'합성 파기 대상',axis:'개인과외',status:'재원',minor:false})).d,p=(await list('products')).d[0];await create('enrollments',{student:s.id,product:p.id,start:'2026-01-01',end:'2026-10-02',division:'개인과외교습자',status:'유효'});sweep('2026-10-02T14:59:59Z');let row=JSON.parse(db.prepare('SELECT data FROM records WHERE id=?').get(s.id).data);assert.equal(row.status,'재원');sweep('2026-10-02T15:00:00Z');row=JSON.parse(db.prepare('SELECT data FROM records WHERE id=?').get(s.id).data);assert.equal(row.status,'종료');assert.equal(row.ended_at,'2026-10-02T15:00:00.000Z');let l=(await create('ledgers',{name:s.name,number:s.number,division:'개인과외교습자',basis_date:'2026-10-03',reviewed:true})).d;assert.ok(db.prepare('SELECT result FROM operations').all().every(x=>!JSON.stringify(x.result).includes('합성')));sweep('2027-04-02T15:00:00Z');assert.equal(db.prepare('SELECT data FROM records WHERE id=?').get(s.id),undefined);assert.ok(db.prepare('SELECT data FROM records WHERE id=?').get(l.id));sweep('2029-10-03T00:00:00Z');assert.equal(db.prepare('SELECT data FROM records WHERE id=?').get(l.id),undefined);setTestClock(null)});
