import {test,beforeEach,after} from 'node:test';import assert from 'node:assert/strict';
process.env.NODE_ENV='test';process.env.DB_PATH=':memory:';
const {server,db,seed,setTestClock,setTestFault,authPolicy,sweep,months,applyDeletionJournal,inspectIntegrity,importBatch,undoImport}=await import('./server.mjs');
const time=Date.parse('2026-10-03T06:00:00Z');await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port;
async function call(p,b,c,m=b?'POST':'GET'){let r=await fetch(base+'/api/'+p,{method:m,headers:{'Content-Type':'application/json',Cookie:c||''},body:b?JSON.stringify(b):undefined});return {status:r.status,d:await r.json(),c:r.headers.get('set-cookie')?.split(';')[0]}}
let ac;const list=async k=>(await call('admin/'+k,null,ac)).d;const create=(k,b)=>call('admin/'+k,{...b,operation_id:crypto.randomUUID()},ac);
beforeEach(async()=>{setTestFault(null);setTestClock(time);db.exec("DELETE FROM records WHERE kind='lessons'; DELETE FROM records WHERE kind='enrollments'");for(const table of ['records','accounts','sessions','operations','audit','verification','account_operations','number_history','policy_runs','retention_jobs','failures','import_mapping','import_batches'])db.exec('DELETE FROM '+table);db.exec('DELETE FROM deletion_journal.entries');db.prepare('DELETE FROM metadata WHERE key=?').run('lifecycle');db.prepare('UPDATE counters SET value=742').run();seed();db.prepare('UPDATE accounts SET initial_until=? WHERE student IS NOT NULL').run(time+authPolicy.initial);ac=(await call('login',{id:'director-demo',password:'Demo-Director-2026!',mode:'director'})).c;});
after(()=>{server.close();db.close()});
const initial=()=>call('login',{id:'MBR-000742',password:'1234',mode:'student'});
const normal=async()=>{let a=await initial();return call('password',{password:'Service-Student-2026!',confirm:'Service-Student-2026!'},a.c)};
test('초기값 만료 경계·재활성화·제한 세션 만료',async()=>{let initialSession=await initial();setTestClock(time+authPolicy.restricted);assert.equal((await call('password',{password:'Service-Student-2026!',confirm:'Service-Student-2026!'},initialSession.c)).status,401);setTestClock(time+authPolicy.initial);assert.equal((await initial()).status,401);ac=(await call('login',{id:'director-demo',password:'Demo-Director-2026!',mode:'director'})).c;let s=(await list('students'))[0];let r=await call('admin/accounts/'+s.id,{operation_id:'reactivate',verified:true,method:'합성 확인'},ac);assert.equal(r.d.initial,true);assert.equal((await initial()).status,200)});
test('계정 발급 장애 후 증적·작업키·인증 모두 롤백',async()=>{let auth=await normal(),s=(await list('students'))[0];const b={operation_id:'atomic-account',verified:true,method:'합성 대면'};for(const point of ['account-after-verification','account-after-credential']){setTestFault(point);assert.equal((await call('admin/accounts/'+s.id,b,ac)).status,500);assert.equal(db.prepare('SELECT count(*) n FROM verification').get().n,0);assert.equal(db.prepare('SELECT count(*) n FROM account_operations').get().n,0);assert.equal((await call('student',null,auth.c)).status,200)}setTestFault(null);let r=await call('admin/accounts/'+s.id,b,ac);assert.ok(r.d.temporary);assert.equal((await call('student',null,auth.c)).status,401);assert.equal((await call('admin/accounts/'+s.id,b,ac)).d.replayed,true)});
test('비밀번호 변경 장애·임시값 소진 장애 원자성',async()=>{let a=await initial();setTestFault('password-after-update');assert.equal((await call('password',{password:'Service-Student-2026!',confirm:'Service-Student-2026!'},a.c)).status,500);assert.equal((await initial()).status,200);setTestFault(null);await normal();let s=(await list('students'))[0],t=(await call('admin/accounts/'+s.id,{verified:true,method:'합성',operation_id:'temp'},ac)).d.temporary;setTestFault('login-after-consume');assert.equal((await call('login',{id:s.number,password:t,mode:'student'})).status,500);assert.equal(db.prepare('SELECT temp_used FROM accounts WHERE student=?').get(s.id).temp_used,0);setTestFault(null);assert.equal((await call('login',{id:s.number,password:t,mode:'student'})).status,200)});
test('번호 정정 동일키 재시도·입력 충돌·장애 롤백',async()=>{let s=(await list('students'))[0],b={number:'MBR-000888',version:s.version,reason:'합성 정정',operation_id:'number'};setTestFault('number-after-update');assert.equal((await call('admin/number-change/'+s.id,b,ac)).status,500);assert.equal((await list('students'))[0].number,s.number);assert.equal(db.prepare('SELECT value FROM counters').get().value,742);setTestFault(null);let r=await call('admin/number-change/'+s.id,b,ac);assert.equal(r.status,200);assert.equal((await call('admin/number-change/'+s.id,b,ac)).d.id,r.d.id);assert.equal((await call('admin/number-change/'+s.id,{...b,number:'MBR-000889'},ac)).status,409);assert.equal(db.prepare('SELECT value FROM counters').get().value,888)});
test('수강 상태 종료 저장 직후 기존 세션·새 로그인 차단',async()=>{let a=await normal(),e=(await list('enrollments'))[0];let r=await call('admin/enrollments/'+e.id,{...e,status:'종료',end:'2026-10-03'},ac,'PUT');assert.equal(r.status,200);assert.equal((await call('student',null,a.c)).status,401);assert.equal((await call('login',{id:'MBR-000742',password:'Service-Student-2026!',mode:'student'})).status,401);assert.equal((await list('students'))[0].ended_at,'2026-10-03T06:00:00.000Z')});
test('KST 공백 없는 전환 유지·공백 있는 미래 등록은 종료',async()=>{let e=(await list('enrollments'))[0];await call('admin/enrollments/'+e.id,{...e,end:'2026-10-03'},ac,'PUT');await create('enrollments',{student:e.student,product:e.product,division:'개인과외교습자',status:'유효',start:'2026-10-04',end:''});sweep('2026-10-03T15:00:00Z');assert.notEqual(JSON.parse(db.prepare('SELECT data FROM records WHERE id=?').get(e.student).data).status,'종료');let next=(await list('enrollments')).find(x=>x.id!==e.id);await call('admin/enrollments/'+next.id,{...next,start:'2026-10-05'},ac,'PUT');sweep('2026-10-03T15:00:00Z');let s=JSON.parse(db.prepare('SELECT data FROM records WHERE id=?').get(e.student).data);assert.equal(s.status,'종료');assert.equal(s.ended_at,'2026-10-03T15:00:00.000Z')});
test('휴원·종료 전 재등록·재활성화·기존 세션 미복구',async()=>{let a=await normal(),s=(await list('students'))[0];await call('admin/students/'+s.id,{...s,status:'휴원'},ac,'PUT');assert.equal((await call('student',null,a.c)).status,200);s=(await list('students'))[0];await call('admin/students/'+s.id,{},ac,'DELETE');s=(await list('students'))[0];await call('admin/students/'+s.id,{...s,status:'재원'},ac,'PUT');assert.equal((await call('student',null,a.c)).status,401);let r=await call('admin/accounts/'+s.id,{verified:true,method:'합성 재등록',operation_id:'again'},ac);assert.ok(r.d.temporary);assert.equal(r.d.initial,undefined);assert.equal((await initial()).status,401)});
test('KST 말일 6개월·파기 실패 재시도·삭제목록 재적용',async()=>{assert.equal(months('2026-08-30T15:00:00Z',6),'2027-02-27T15:00:00.000Z');let s=(await list('students'))[0];await call('admin/students/'+s.id,{},ac,'DELETE');let snapshot=db.prepare('SELECT * FROM records WHERE id=?').get(s.id);setTestFault('purge-after-delete');assert.throws(()=>sweep('2027-04-03T06:00:00Z'));assert.ok(db.prepare('SELECT * FROM records WHERE id=?').get(s.id));assert.equal(db.prepare('SELECT status FROM retention_jobs WHERE target=?').get(s.id).status,'실패');assert.equal(db.prepare('SELECT count(*) n FROM deletion_journal.entries').get().n,0);setTestFault(null);sweep('2027-04-03T06:00:00Z');assert.equal(db.prepare('SELECT * FROM records WHERE id=?').get(s.id),undefined);assert.equal(db.prepare('SELECT status FROM retention_jobs WHERE target=?').get(s.id).status,'완료');db.prepare('INSERT INTO records(kind,id,data,version) VALUES(?,?,?,?)').run(snapshot.kind,snapshot.id,snapshot.data,snapshot.version);assert.equal(applyDeletionJournal().removed,1);assert.equal(inspectIntegrity().ok,true)});

const fixture=()=>({batch_id:'synthetic-batch',source:{file:'합성 v1.1 스냅샷',tab_id:1284097826,header_row:4,version:'v1.1'},cutoff:'2026-10-03T06:00:00Z',students:[{source_key:'synthetic-s1',number:'MBR-000950',name:'합성 이관 학생',axis:'개인과외',status:'재원',minor:false}],products:[{source_key:'p1',name:'합성 이관 상품',axis:'개인과외',status:'사용',duration:'50분'}],enrollments:[{source_key:'e1',student_key:'synthetic-s1',product_key:'p1',start:'2026-10-01',end:'',division:'개인과외교습자',status:'유효'}],lessons:[{source_key:'l1',student_key:'synthetic-s1',enrollment_key:'e1',date:'2026-10-02',time:'14:00',status:'완료',type:'정규',song:'합성 곡',published:false},{source_key:'template'}]});
test('이관 배치·템플릿 제외·중복 재시도·최댓값·초기 비활성',async()=>{let input=fixture(),preview=await call('admin/import-preview',input,ac);assert.equal(preview.d.ok,true);assert.equal(preview.d.excluded.length,1);let first=importBatch(input);assert.equal(first.replayed,false);assert.equal(importBatch(input).replayed,true);assert.equal((await list('students')).filter(s=>s.number==='MBR-000950').length,1);assert.equal(db.prepare('SELECT value FROM counters').get().value,950);assert.equal((await call('login',{id:'MBR-000950',password:'1234',mode:'student'})).status,401);assert.equal((await list('lessons')).find(l=>l.song==='합성 곡').published,false);assert.equal(inspectIntegrity().ok,true)});
test('이관 누락참조·보강 완료 불명확·메타데이터/기간 오류 보류',async()=>{for(const mutate of [x=>x.source.header_row=5,x=>x.enrollments[0].student_key='missing',x=>x.lessons[0].status='보강',x=>x.students.push({...x.students[0],source_key:'s2'}),x=>x.enrollments.push({...x.enrollments[0],source_key:'e2'}),x=>x.lessons[0].published=true]){let input=fixture();mutate(input);assert.equal((await call('admin/import-preview',input,ac)).d.ok,false);assert.throws(()=>importBatch(input));assert.equal((await list('students')).length,1)}});
test('운영 시작 후 이관 잠금·운영값 덮어쓰기 방지',async()=>{const input=fixture();importBatch(input);let s=(await list('students')).find(s=>s.number==='MBR-000950');await call('admin/students/'+s.id,{...s,goal:'웹에서 바꾼 목표'},ac,'PUT');assert.equal(importBatch(input).replayed,true);assert.equal((await list('students')).find(x=>x.id===s.id).goal,'웹에서 바꾼 목표');assert.throws(()=>undoImport(input.batch_id));db.prepare('INSERT OR REPLACE INTO metadata VALUES(?,?)').run('lifecycle','operating');assert.throws(()=>importBatch({...input,batch_id:'new'}));assert.throws(()=>undoImport(input.batch_id))});
test('운영 전 배치 되돌림·번호 재사용 방지',async()=>{let input=fixture();importBatch(input);assert.equal(undoImport(input.batch_id).replayed,false);assert.equal(undoImport(input.batch_id).replayed,true);assert.equal((await list('students')).length,1);assert.equal(db.prepare('SELECT value FROM counters').get().value,950);assert.ok(db.prepare('SELECT * FROM number_history WHERE number=?').get('MBR-000950'));assert.throws(()=>importBatch(input))});
test('학생 수업 상세 소유권·비공개 차단·월/페이지/범위 검증',async()=>{let auth=await normal(),s=(await list('students'))[0],e=(await list('enrollments'))[0];for(let i=1;i<=12;i++)await create('lessons',{student:s.id,enrollment:e.id,date:'2026-10-'+String(i).padStart(2,'0'),time:'15:00',status:'완료',type:'정규',published:true,song:'합성 이력 '+i,internal:'학생에게 숨김'});let history=await call('student/lessons?page=2&size=10&month=2026-10',null,auth.c);assert.equal(history.d.total,13);assert.equal(history.d.items.length,3);let detail=await call('student/lessons/'+history.d.items[0].id,null,auth.c);assert.equal(detail.status,200);assert.equal(detail.d.internal,undefined);assert.equal((await call('student/lessons/999999',null,auth.c)).status,404);let hidden=(await create('lessons',{student:s.id,enrollment:e.id,date:'2026-10-15',time:'15:00',status:'완료',type:'정규',published:false})).d;assert.equal((await call('student/lessons/'+hidden.id,null,auth.c)).status,404);assert.equal((await call('student/lessons?size=999',null,auth.c)).status,400);assert.equal((await call('student/lessons?month=bad',null,auth.c)).status,400);assert.equal((await call('student/lessons?month=2025-01',null,auth.c)).d.total,0)});
test('최신 공개 수업 과제 없음·이전 과제 자동 승계 없음',async()=>{let auth=await normal(),s=(await list('students'))[0],e=(await list('enrollments'))[0];await create('lessons',{student:s.id,enrollment:e.id,date:'2026-10-03',time:'14:00',status:'완료',type:'정규',published:true,task:''});let view=(await call('student',null,auth.c)).d;assert.equal(view.lessons.length,1);assert.equal(view.lessons[0].task,'')});
test('대장 3년 독립 파기 실패·일반 정보와 별도 유지',async()=>{let s=(await list('students'))[0];await create('ledgers',{number:s.number,name:'합성 대장',division:'교습소',basis_date:'2026-10-03',reviewed:true});await call('admin/students/'+s.id,{},ac,'DELETE');sweep('2027-04-03T06:00:00Z');assert.equal(db.prepare("SELECT count(*) n FROM records WHERE kind='students'").get().n,0);assert.equal(db.prepare("SELECT count(*) n FROM records WHERE kind='ledgers'").get().n,1);setTestFault('ledger-after-delete');assert.throws(()=>sweep('2029-10-03T06:00:00Z'));assert.equal(db.prepare("SELECT count(*) n FROM records WHERE kind='ledgers'").get().n,1);setTestFault(null);sweep('2029-10-03T06:00:00Z');assert.equal(db.prepare("SELECT count(*) n FROM records WHERE kind='ledgers'").get().n,0)});

test('수정 응답 유실 재시도·작업키 입력 충돌',async()=>{let s=(await list('students'))[0],body={...s,name:'합성 수정',operation_id:'edit-once'};let first=await call('admin/students/'+s.id,body,ac,'PUT');assert.equal(first.status,200);let second=await call('admin/students/'+s.id,body,ac,'PUT');assert.equal(second.status,200);assert.equal(second.d.version,first.d.version);assert.equal((await call('admin/students/'+s.id,{...body,name:'다른 입력'},ac,'PUT')).status,409)});

test('생산 모드 인증 출처·Secure 쿠키·잘못된 모드/입력 거절',async()=>{process.env.APP_MODE='production';process.env.PUBLIC_ORIGIN='https://synthetic.example';try{assert.equal((await call('login',{id:'director-demo',password:'Demo-Director-2026!',mode:'director'})).status,403);const response=await fetch(base+'/api/login',{method:'POST',headers:{'Content-Type':'application/json',Origin:process.env.PUBLIC_ORIGIN},body:JSON.stringify({id:'director-demo',password:'Demo-Director-2026!',mode:'director'})});assert.equal(response.status,200);assert.ok(response.headers.get('set-cookie').includes('; Secure'));}finally{delete process.env.APP_MODE;delete process.env.PUBLIC_ORIGIN}assert.equal((await call('login',{id:'director-demo',password:'Demo-Director-2026!',mode:'invalid'})).status,401);assert.equal((await call('login',{id:{},password:'x',mode:'student'})).status,401)});

test('T-37 파기 전 재등록 원자성·기한 도래 시 새 학생/번호',async()=>{let s=(await list('students'))[0];await call('admin/students/'+s.id,{},ac,'DELETE');s=(await list('students'))[0];const p=(await list('products'))[0];let b={operation_id:'reregister',version:s.version,verified:true,method:'합성 재등록 확인',product:p.id,start:'2026-10-03',division:'개인과외교습자'};setTestFault('reregister-after-save');assert.equal((await call('admin/re-enroll/'+s.id,b,ac)).status,500);assert.equal((await list('students'))[0].status,'종료');assert.equal((await list('enrollments')).length,1);setTestFault(null);assert.equal((await call('admin/re-enroll/'+s.id,b,ac)).status,200);assert.equal((await call('admin/re-enroll/'+s.id,b,ac)).status,200);s=(await list('students'))[0];assert.equal(s.number,'MBR-000742');assert.equal(s.delete_due,null);await call('admin/students/'+s.id,{},ac,'DELETE');s=(await list('students'))[0];setTestClock(Date.parse(s.delete_due));ac=(await call('login',{id:'director-demo',password:'Demo-Director-2026!',mode:'director'})).c;let rs=await Promise.all([call('admin/re-enroll/'+s.id,{...b,version:s.version,operation_id:'cutoff',start:'2027-04-03'},ac),create('students',{name:'파기 후 합성 새 학생',axis:'개인과외',status:'재원',minor:false})]);assert.equal(rs[0].status,404);assert.equal(rs[1].status,200);assert.notEqual(rs[1].d.id,s.id);assert.notEqual(rs[1].d.number,s.number)});
test('T-41 교습소→개인과외 순차 전환·과거 대장 소속·학생 대장 제외',async()=>{let a=await normal(),s=(await list('students'))[0];await create('ledgers',{number:s.number,name:'합성 과거 대장',division:'교습소',basis_date:'2026-10-03',reviewed:true});let e=(await list('enrollments'))[0];let r=await call('admin/transition/'+e.id,{operation_id:'division-transition',version:e.version,start:'2026-10-03',end:'',product:e.product,division:'개인과외교습자'},ac);assert.equal(r.status,200);assert.equal((await list('ledgers'))[0].division,'교습소');let view=await call('student',null,a.c);assert.equal(view.status,200);assert.equal(view.d.number,s.number);assert.equal(view.d.ledgers,undefined);assert.equal(inspectIntegrity().ok,true)});

test('저장소 번호/계정 유일성·관계 참조·연결 삭제 제약',async()=>{let s=(await list('students'))[0];assert.throws(()=>db.prepare('INSERT INTO records(kind,data) VALUES(?,?)').run('students',JSON.stringify({number:s.number,name:'합성 중복'})));assert.throws(()=>db.prepare('INSERT INTO records(kind,data) VALUES(?,?)').run('enrollments',JSON.stringify({student:999999,product:999999})));assert.throws(()=>db.prepare('DELETE FROM records WHERE id=?').run(s.id));assert.throws(()=>db.prepare('INSERT INTO accounts(id,student) VALUES(?,?)').run('duplicate-account',s.id));assert.equal(inspectIntegrity().ok,true)});
