import {test,after} from 'node:test';
import assert from 'node:assert/strict';
process.env.NODE_ENV='test';process.env.DB_PATH=':memory:';
const {server,db,months}=await import('./server.mjs');
await new Promise(r=>server.listen(0,'127.0.0.1',r));let base='http://127.0.0.1:'+server.address().port;
async function call(url,body,cookie,method=body?'POST':'GET'){let r=await fetch(base+'/api/'+url,{method,headers:{'Content-Type':'application/json',Cookie:cookie||''},body:body?JSON.stringify(body):undefined});return {status:r.status,data:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]}}
after(()=>server.close());
test('합성 MVP 서버 수용 검증',async()=>{
 let admin=await call('login',{id:'director-demo',password:'Demo-Director-2026!',mode:'director'});assert.equal(admin.status,200);let ac=admin.cookie;
 let student=await call('login',{id:'MBR-000742',password:'1234',mode:'student'});assert.equal(student.data.restricted,true);assert.equal((await call('student',null,student.cookie)).status,403);assert.equal((await call('admin/students',null,student.cookie)).status,403);
 assert.equal((await call('login',{id:'MBR-000742',password:'1234',mode:'director'})).status,401);
 let change=await call('password',{password:'Student-New-2026!',confirm:'Student-New-2026!'},student.cookie);assert.equal(change.status,200);let sc=change.cookie;assert.equal((await call('student',null,student.cookie)).status,401);let view=await call('student',null,sc);assert.equal(view.status,200);assert.ok(!JSON.stringify(view.data).includes('내부'));assert.ok(!('contact' in view.data));assert.equal((await call('student?id=999',null,sc)).status,403);assert.equal((await call('admin/students',null,sc)).status,403);
 let body={name:'가상 미성년 학생',axis:'개인과외',status:'재원',minor:true,contact:'',guardian:'',guardian_contact:'',operation_id:'student-a'};
 let [x,y]=await Promise.all([call('admin/students',body,ac),call('admin/students',{...body,name:'가상 학생 B',operation_id:'student-b'},ac)]);assert.equal(x.data.number,'MBR-000743');assert.equal(y.data.number,'MBR-000744');assert.equal((await call('admin/students',body,ac)).data.id,x.data.id);assert.equal(db.prepare('SELECT value FROM counters').get().value,744);
 assert.equal((await call('login',{id:x.data.number,password:'1234',mode:'student'})).status,401);
 let products=(await call('admin/products',null,ac)).data;let enrollment={student:x.data.id,product:products[0].id,start:'2026-10-01',end:'2026-12-31',division:'교습소',schedule:'월요일 13:00',status:'유효',operation_id:'enroll-a'};
 let [e1,e2]=await Promise.all([call('admin/enrollments',enrollment,ac),call('admin/enrollments',{...enrollment,division:'개인과외교습자',operation_id:'enroll-b'},ac)]);assert.equal(e1.status,200);assert.equal(e2.status,409);
 assert.equal((await call('admin/enrollments',{...enrollment,start:'2027-01-01',end:'2027-02-01',operation_id:'enroll-c'},ac)).status,200);
 let s=x.data;let updated=await call('admin/students/'+s.id,{...s,name:'가상 수정'},ac,'PUT');assert.equal(updated.status,200);assert.equal((await call('admin/students/'+s.id,s,ac,'PUT')).status,409);
 let first=(await call('admin/students',null,ac)).data.find(s=>s.number==='MBR-000742');assert.equal((await call('admin/students/'+first.id,{...first,status:'휴원'},ac,'PUT')).status,200);assert.equal((await call('student',null,sc)).status,200);
 let temp=await call('admin/accounts/'+first.id,{operation_id:crypto.randomUUID(),verified:true,method:'합성 대면 확인'},ac);assert.ok(temp.data.temporary);assert.equal((await call('student',null,sc)).status,401);let reset=await call('login',{id:first.number,password:temp.data.temporary,mode:'student'});assert.equal(reset.data.restricted,true);assert.equal((await call('login',{id:first.number,password:temp.data.temporary,mode:'student'})).status,401);assert.equal((await call('student',null,reset.cookie)).status,403);
 let reissue=await call('admin/accounts/'+first.id,{operation_id:crypto.randomUUID(),verified:true,method:'합성 재확인'},ac);assert.equal((await call('password',{password:'Another-New-2026!',confirm:'Another-New-2026!'},reset.cookie)).status,401);let fresh=await call('login',{id:first.number,password:reissue.data.temporary,mode:'student'});let newpass=await call('password',{password:'Another-New-2026!',confirm:'Another-New-2026!'},fresh.cookie);assert.equal(newpass.status,200);
 assert.equal((await call('admin/students/'+first.id,{},ac,'DELETE')).status,200);assert.equal((await call('student',null,newpass.cookie)).status,401);assert.equal((await call('login',{id:first.number,password:'Another-New-2026!',mode:'student'})).status,401);
 let ended=(await call('admin/students',null,ac)).data.find(s=>s.id===first.id);assert.equal(ended.status,'종료');assert.equal(ended.delete_due,months(ended.ended_at,6));assert.equal(months('2026-08-31T12:00:00Z',6),'2027-02-28T12:00:00.000Z');
 for(let [i,division] of ['교습소','개인과외교습자'].entries()){let ledger=await call('admin/ledgers',{number:first.number,name:'가상 보존 학생',division,basis_date:'2026-10-03',reviewed:true,operation_id:'ledger'+i},ac);assert.equal(ledger.status,200);assert.equal(ledger.data.retain_until,'2029-10-02T15:00:00.000Z');assert.ok(ledger.data.basis.includes('미검수'))}
 db.prepare('UPDATE records SET data=? WHERE id=?').run(JSON.stringify({...ended,delete_due:'2000-01-01T00:00:00Z'}),first.id);await call('admin/retention',{},ac);assert.ok(!(await call('admin/students',null,ac)).data.some(s=>s.id===first.id));assert.equal((await call('admin/ledgers',null,ac)).data.length,2);assert.equal(db.prepare('SELECT * FROM accounts WHERE student=?').get(first.id),undefined);assert.ok(!(await call('admin/lessons',null,ac)).data.some(l=>l.student===first.id));
 let ledgers=(await call('admin/ledgers',null,ac)).data;for(let l of ledgers)db.prepare('UPDATE records SET data=? WHERE id=?').run(JSON.stringify({...l,retain_until:'2000-01-01T00:00:00Z'}),l.id);await call('admin/retention',{},ac);assert.equal((await call('admin/ledgers',null,ac)).data.length,0);
 let preview=await call('admin/import-preview',{rows:[{number:'MBR-000743',name:'가상'},{number:'bad',name:''}]},ac);assert.ok(preview.data.every(r=>r.errors.length));
 for(let i=0;i<5;i++)await call('login',{id:'missing',password:'bad',mode:'student'});assert.equal((await call('login',{id:'missing',password:'bad',mode:'student'})).status,429);
});
